services:
  app:
    build: docker/development/node/
    working_dir: /frontend/
    command: pnpm run --filter @project/app serve
    volumes:
      - ./frontend/:/frontend/
    ports:
      - ${APP_DEVELOPMENT_SERVER_PORT:-80}:80
    environment:
      - APP_DEVELOPMENT_SERVER_PORT

  frontend-node-cli:
    build: docker/development/node/
    working_dir: /frontend/
    volumes:
      - ./frontend/:/frontend/
