services:
  app:
    build: docker/development/node/
    working_dir: /app/
    command: pnpm run serve
    volumes:
      - ./app/:/app/
    ports:
      - ${APP_DEVELOPMENT_SERVER_PORT:-80}:80
    environment:
      - APP_DEVELOPMENT_SERVER_PORT
  app-node-cli:
    build: docker/development/node/
    working_dir: /app/
    volumes:
      - ./app/:/app/
